# Site settings
title: Let's Shoot’Em Up
email:
description: > # this means to ignore newlines until "baseurl:"
  "Let's Shoot’Em Up" is a roguelike-shmup video game for Android and WebBrowser made by Vikings Entertainement.
  "Let's Shoot’Em Up" is a frenetic space shooter. 

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: xxxxxxx
data-ad-client: ca-pub-xxxxxxxxxxxxxxxxxx
google_ad_client: ca-pub-xxxxxxxxxxxxxxxxxx

google_analytics: "UA-96251082-1"
addthis_id: ra-xxxxxxxxxxxx
disqus_account: v1kings

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  #- title: twitter
  #  url: https://twitter.com/v1kings
  #- title: facebook
  #  url: https://facebook.com/v1kings
  #- title: google-plus
  #  url: https://plus.google.com/+v1kings
  - title: github
    url: https://github.com/achorein/letsshootemup-unity

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
